eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true 
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
      
microservice:
  user-service:
    endpoints:
      endpoint:
        uri: http://192.168.1.10:8082/user/create-user-detail
